# Generated by Django 5.2.14 on 2026-05-27 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0012_add_ma_sos_race_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENRElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=200)),
                ('election_date', models.DateField()),
                ('scope', models.CharField(choices=[('state', 'State'), ('county', 'County')], max_length=10)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('eid', models.IntegerField()),
                ('enr_base_url', models.URLField()),
                ('enr_resolved_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('link_confidence', models.CharField(choices=[('auto', 'Auto-linked'), ('ambiguous', 'Ambiguous — manual review needed'), ('manual', 'Manually linked')], default='auto', max_length=20)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enr_elections', to='elections.election')),
            ],
            options={
                'ordering': ['-election_date', 'scope', 'county'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('county__isnull', False)), fields=('eid', 'county'), name='unique_enr_county_election'), models.UniqueConstraint(condition=models.Q(('county__isnull', True)), fields=('eid',), name='unique_enr_state_election')],
            },
        ),
    ]
