# Generated by Django 5.2.14 on 2026-10-02 13:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client this key belongs to, e.g. "CivicData".', max_length=120)),
                ('owner', models.CharField(blank=True, help_text='Contact person or organization.', max_length=200)),
                ('prefix', models.CharField(editable=False, max_length=32, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('access_level', models.CharField(choices=[('read', 'Read'), ('read_write', 'Read / write')], default='read', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('throttle_rate', models.CharField(blank=True, help_text="e.g. '1000/hour'. Blank uses CIVICMIRROR_API_KEY_DEFAULT_RATE; 'none' disables throttling.", max_length=32, validators=[api.models.validate_throttle_rate])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['name', 'created_at'],
            },
        ),
    ]
