# Generated by Django 5.2.14 on 2026-05-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE accounts_userprofile DROP COLUMN IF EXISTS terms_accepted_at;',
                'ALTER TABLE accounts_userprofile DROP COLUMN IF EXISTS terms_version;',
            ],
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(model_name='userprofile', name='terms_accepted_at'),
                migrations.RemoveField(model_name='userprofile', name='terms_version'),
            ],
        ),
    ]
