# Generated by Django 5.2.14 on 2026-05-25 10:21

from django.db import migrations


def drop_legacy_terms_columns(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE accounts_userprofile DROP COLUMN IF EXISTS terms_accepted_at;')
        schema_editor.execute('ALTER TABLE accounts_userprofile DROP COLUMN IF EXISTS terms_version;')
    elif connection.vendor == 'sqlite':
        # Local/test DBs: without this, the leftover NOT NULL terms_version breaks UserProfile inserts.
        with connection.cursor() as cursor:
            columns = {c.name for c in connection.introspection.get_table_description(cursor, 'accounts_userprofile')}
        for column in ('terms_accepted_at', 'terms_version'):
            if column in columns:
                schema_editor.execute(f'ALTER TABLE accounts_userprofile DROP COLUMN {column};')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_legacy_terms_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(model_name='userprofile', name='terms_accepted_at'),
                migrations.RemoveField(model_name='userprofile', name='terms_version'),
            ],
        ),
    ]
