# Generated by Django 5.2.14 on 2026-05-25 10:21

from django.db import migrations


def drop_legacy_terms_columns(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('ALTER TABLE accounts_userprofile DROP COLUMN IF EXISTS terms_accepted_at;')
    schema_editor.execute('ALTER TABLE accounts_userprofile DROP COLUMN IF EXISTS terms_version;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_legacy_terms_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(model_name='userprofile', name='terms_accepted_at'),
                migrations.RemoveField(model_name='userprofile', name='terms_version'),
            ],
        ),
    ]
