# Generated by Django 5.2.17 on 2026-08-13 20:55

import cm2_core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cm2_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('election_date', models.DateField()),
                ('election_type', models.CharField(choices=[('general', 'General'), ('primary', 'Primary'), ('primary_runoff', 'Primary runoff'), ('general_runoff', 'General runoff'), ('special', 'Special'), ('municipal', 'Municipal'), ('other', 'Other')], max_length=24)),
                ('lifecycle_status', models.CharField(choices=[('provisional', 'Provisional'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('results_pending', 'Results pending'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='provisional', max_length=24)),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['election_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('state', 'State'), ('congressional_district', 'Congressional district'), ('state_legislative_district', 'State legislative district'), ('county', 'County'), ('municipality', 'Municipality'), ('judicial_district', 'Judicial district'), ('school_district', 'School district'), ('other', 'Other')], max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('active_start', models.DateField(blank=True, null=True)),
                ('active_end', models.DateField(blank=True, null=True)),
                ('record_status', models.CharField(choices=[('provisional', 'Provisional'), ('verified', 'Verified'), ('inactive', 'Inactive')], default='provisional', max_length=16)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cm2_elections.jurisdiction')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['state', 'classification', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('canonical_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=64)),
                ('default_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('positions', models.PositiveSmallIntegerField(default=1)),
                ('record_status', models.CharField(choices=[('provisional', 'Provisional'), ('verified', 'Verified'), ('inactive', 'Inactive')], default='provisional', max_length=16)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='cm2_elections.jurisdiction')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['jurisdiction__state', 'canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('party_contest', models.CharField(blank=True, max_length=100)),
                ('vote_for', models.PositiveSmallIntegerField(default=1)),
                ('is_partisan', models.BooleanField(default=False)),
                ('is_unexpired', models.BooleanField(default=False)),
                ('lifecycle_status', models.CharField(choices=[('provisional', 'Provisional'), ('upcoming', 'Upcoming'), ('active', 'Active'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='provisional', max_length=16)),
                ('result_status', models.CharField(choices=[('pending', 'Pending'), ('unofficial', 'Unofficial'), ('official', 'Official'), ('certified', 'Certified'), ('corrected', 'Corrected')], default='pending', max_length=16)),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='cm2_elections.election')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='cm2_elections.office')),
            ],
            options={
                'ordering': ['election__election_date', 'office__canonical_name', 'party_contest'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('canonical_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, max_length=32)),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('family_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=32)),
                ('identity_state', models.CharField(choices=[('provisional', 'Provisional'), ('resolved', 'Resolved'), ('disputed', 'Disputed'), ('merged', 'Merged')], default='provisional', max_length=16)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_records', to='cm2_elections.person')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['family_name', 'given_name', 'canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('method_of_selection', models.CharField(choices=[('election', 'Election'), ('appointment', 'Appointment'), ('succession', 'Succession'), ('other', 'Other')], max_length=16)),
                ('role', models.CharField(max_length=64)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='cm2_elections.office')),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_terms', to='cm2_elections.person')),
            ],
            options={
                'ordering': ['-start_date', 'office'],
            },
        ),
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=255)),
                ('verification_method', models.CharField(choices=[('source', 'Official source'), ('human_review', 'Human review'), ('existing_link', 'Existing approved link')], default='source', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='cm2_elections.person')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheme', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='PersonSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_key', models.CharField(max_length=512)),
                ('reported_name', models.CharField(max_length=255)),
                ('ballot_name', models.CharField(blank=True, max_length=255)),
                ('prefix', models.CharField(blank=True, max_length=32)),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('family_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=32)),
                ('filing_data', models.JSONField(blank=True, default=dict)),
                ('protected_address', models.TextField(blank=True)),
                ('protected_phone', models.CharField(blank=True, max_length=64)),
                ('protected_email', models.EmailField(blank=True, max_length=254)),
                ('parser_version', models.CharField(max_length=64)),
                ('retrieval_context', models.JSONField(blank=True, default=dict)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='cm2_elections.person')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_source_records', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['source_artifact', 'source_row_key'],
            },
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_key', models.CharField(blank=True, max_length=512)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('ballot_name', models.CharField(max_length=255)),
                ('party_candidate', models.CharField(blank=True, max_length=100)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified'), ('write_in', 'Write-in'), ('provisional', 'Provisional')], default='active', max_length=16)),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cm2_core.sourceartifact')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidacies', to='cm2_elections.contest')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidacies', to='cm2_elections.person')),
                ('source_records', models.ManyToManyField(blank=True, related_name='candidacies', to='cm2_elections.personsourcerecord')),
            ],
            options={
                'ordering': ['contest', 'ballot_name'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['election_date', 'election_type', 'lifecycle_status'], name='cm2_electio_electio_1bac18_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdiction',
            index=models.Index(fields=['state', 'classification', 'record_status'], name='cm2_electio_state_7c9162_idx'),
        ),
        migrations.AddConstraint(
            model_name='jurisdiction',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent')), _negated=True), name='cm2_juris_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='jurisdiction',
            constraint=models.CheckConstraint(condition=models.Q(('active_start__isnull', True), ('active_end__isnull', True), ('active_end__gte', models.F('active_start')), _connector='OR'), name='cm2_juris_active_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['jurisdiction', 'record_status'], name='cm2_electio_jurisdi_5c7cf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('positions__gt', 0)), name='cm2_office_positions_positive'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('default_term_months__isnull', True), ('default_term_months__gt', 0), _connector='OR'), name='cm2_office_term_months_positive'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['election', 'lifecycle_status', 'result_status'], name='cm2_electio_electio_7e4917_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['office', 'party_contest'], name='cm2_electio_office__526ded_idx'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.CheckConstraint(condition=models.Q(('vote_for__gt', 0)), name='cm2_contest_vote_for_positive'),
        ),
        migrations.AddConstraint(
            model_name='contest',
            constraint=models.UniqueConstraint(fields=('election', 'office', 'party_contest', 'is_unexpired'), name='cm2_contest_identity_uniq'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['identity_state', 'family_name', 'given_name'], name='cm2_electio_identit_a76a8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_state', 'merged'), ('merged_into__isnull', False)), models.Q(models.Q(('identity_state', 'merged'), _negated=True), ('merged_into__isnull', True)), _connector='OR'), name='cm2_person_merge_target_valid'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('merged_into')), _negated=True), name='cm2_person_no_self_merge'),
        ),
        migrations.AddConstraint(
            model_name='officeterm',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='cm2_office_term_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='officeterm',
            constraint=models.UniqueConstraint(fields=('person', 'office', 'start_date', 'role'), name='cm2_office_term_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='personidentifier',
            constraint=models.UniqueConstraint(fields=('scheme', 'identifier'), name='cm2_person_identifier_global_uniq'),
        ),
        migrations.AddConstraint(
            model_name='personidentifier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_method', 'human_review'), _negated=True), models.Q(('verified_by__isnull', False), ('verified_at__isnull', False)), _connector='OR'), name='cm2_identifier_review_metadata'),
        ),
        migrations.AddConstraint(
            model_name='personsourcerecord',
            constraint=models.UniqueConstraint(fields=('source_artifact', 'source_row_key'), name='cm2_person_source_lineage_uniq'),
        ),
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(fields=('person', 'contest'), name='cm2_candidacy_person_contest_uniq'),
        ),
    ]
