# Generated by Django 5.2.17 on 2026-08-16 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm2_elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status changed'), ('note_added', 'Note added')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cm2_lifecycle_audit_events', to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_audit_events', to='cm2_elections.contest')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_audit_events', to='cm2_elections.election')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'created_at'], name='cm2_electio_electio_66bfd6_idx'), models.Index(fields=['contest', 'created_at'], name='cm2_electio_contest_2a3bea_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contest__isnull', True), ('election__isnull', False)), models.Q(('contest__isnull', False), ('election__isnull', True)), _connector='OR'), name='cm2_lifecycle_event_single_subject')],
            },
        ),
    ]
