# Generated by Django 4.2.30 on 2026-05-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_count", models.BigIntegerField(default=0)),
                (
                    "vote_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("unofficial", "Unofficial"),
                        ],
                        default="unofficial",
                        max_length=20,
                    ),
                ),
                ("is_winner", models.BooleanField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_results",
                        to="elections.candidate",
                    ),
                ),
                (
                    "measure_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_results",
                        to="elections.measureoption",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_results",
                        to="elections.race",
                    ),
                ),
            ],
            options={
                "ordering": ["-vote_count", "id"],
                "indexes": [
                    models.Index(fields=["race"], name="results_off_race_id_ae5d9d_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="officialresult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("candidate__isnull", False), ("measure_option__isnull", True)
                    ),
                    models.Q(
                        ("candidate__isnull", True), ("measure_option__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="exactly_one_result_target",
            ),
        ),
    ]
