# Generated by Django 4.2.30 on 2026-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("results", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officialresult",
            options={"ordering": ["round_number", "-vote_count", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="officialresult",
            name="exactly_one_result_target",
        ),
        migrations.RemoveIndex(
            model_name="officialresult",
            name="results_off_race_id_ae5d9d_idx",
        ),
        migrations.AddField(
            model_name="officialresult",
            name="is_write_in_aggregate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="officialresult",
            name="jurisdiction_fragment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="officialresult",
            name="round_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="officialresult",
            index=models.Index(
                fields=["race", "round_number"], name="results_off_race_id_2c08aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialresult",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_write_in_aggregate", True),
                    models.Q(
                        ("candidate__isnull", False), ("measure_option__isnull", True)
                    ),
                    models.Q(
                        ("candidate__isnull", True), ("measure_option__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="result_target_valid",
            ),
        ),
    ]
