# Generated by Django 5.2.14 on 2026-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePrecedence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='*', help_text="2-letter state or '*' for all", max_length=2)),
                ('field_group', models.CharField(default='*', help_text="field group or '*' for all", max_length=40)),
                ('source', models.CharField(max_length=40)),
                ('rank', models.IntegerField(default=0, help_text='lower = higher precedence')),
            ],
            options={
                'ordering': ['state', 'field_group', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('state', 'field_group', 'source'), name='unique_precedence_state_group_source')],
            },
        ),
    ]
