# Generated by Django 5.2.14 on 2026-05-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0007_seed_ia_sos_precedence'),
        ('aggregation', '0008_seed_sc_enr_precedence'),
        ('aggregation', '0009_seed_fec_openstates_precedence'),
    ]

    operations = [
    ]
