# Generated by Django 5.2.17 on 2026-08-13 21:06

import cm2_core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cm2_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_key', models.CharField(max_length=512, unique=True)),
                ('state', models.CharField(max_length=2)),
                ('source_system', models.CharField(max_length=64)),
                ('capability', models.CharField(choices=[('pre_election', 'Pre-election'), ('results', 'Results'), ('certification', 'Certification'), ('civic_data', 'Civic-Data comparison')], max_length=24)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial'), ('unchanged', 'Unchanged')], default='started', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('aggregate_counts', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.CharField(blank=True, max_length=255)),
                ('source_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_logs', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('details', models.JSONField(default=dict)),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_reports', to='cm2_core.sourceartifact')),
                ('sync_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='cm2_ingestion.synclog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['state', 'capability', 'status', 'started_at'], name='cm2_ingesti_state_edd8d6_idx'),
        ),
    ]
