# Generated by Django 5.2.17 on 2026-08-13 20:55

import cm2_core.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cm2_elections', '0001_initial'),
        ('cm2_results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityReviewCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('case_type', models.CharField(choices=[('person_identity', 'Person identity'), ('fuzzy_person_match', 'Fuzzy person match'), ('unresolved_result_choice', 'Unresolved result choice')], max_length=32)),
                ('deduplication_key', models.CharField(max_length=512, unique=True)),
                ('supporting_evidence', models.JSONField(blank=True, default=dict)),
                ('conflicting_evidence', models.JSONField(blank=True, default=dict)),
                ('has_private_evidence', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('superseded', 'Superseded')], default='open', max_length=16)),
                ('resolution_action', models.CharField(blank=True, choices=[('link_existing', 'Link existing'), ('confirm_new', 'Confirm new'), ('merge_people', 'Merge people'), ('link_civic_data', 'Link Civic-Data'), ('defer', 'Defer')], max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('provisional_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_review_cases', to='cm2_elections.person')),
                ('result_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_review_cases', to='cm2_results.resultchoice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cm2_identity_reviews', to=settings.AUTH_USER_MODEL)),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_review_cases', to='cm2_elections.personsourcerecord')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_cases', to='cm2_review.identityreviewcase')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityReviewSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_scheme', models.CharField(blank=True, max_length=64)),
                ('external_identifier', models.CharField(blank=True, max_length=255)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('supporting_evidence', models.JSONField(blank=True, default=dict)),
                ('conflicting_evidence', models.JSONField(blank=True, default=dict)),
                ('uses_private_evidence', models.BooleanField(default=False)),
                ('review_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='cm2_review.identityreviewcase')),
                ('suggested_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_review_suggestions', to='cm2_elections.person')),
            ],
            options={
                'ordering': ['review_case', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='identityreviewcase',
            index=models.Index(fields=['status', 'case_type', 'created_at'], name='cm2_review__status_4af7d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewcase',
            constraint=models.CheckConstraint(condition=models.Q(('source_record__isnull', False), ('provisional_person__isnull', False), ('result_choice__isnull', False), _connector='OR'), name='cm2_review_case_subject_required'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'rejected']), _negated=True), models.Q(('reviewed_by__isnull', False), ('reviewed_at__isnull', False), models.Q(('resolution_action', ''), _negated=True)), _connector='OR'), name='cm2_review_terminal_metadata'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewcase',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('superseded_by')), _negated=True), name='cm2_review_no_self_supersede'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewsuggestion',
            constraint=models.UniqueConstraint(fields=('review_case', 'rank'), name='cm2_review_suggestion_rank_uniq'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gt', 0)), name='cm2_review_suggestion_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', Decimal('0')), ('score__lte', Decimal('1'))), _connector='OR'), name='cm2_review_suggestion_score_valid'),
        ),
        migrations.AddConstraint(
            model_name='identityreviewsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('suggested_person__isnull', False), ('external_scheme', ''), ('external_identifier', '')), models.Q(('suggested_person__isnull', True), models.Q(('external_scheme', ''), _negated=True), models.Q(('external_identifier', ''), _negated=True)), _connector='OR'), name='cm2_review_suggestion_target_valid'),
        ),
    ]
