# Generated by Django 5.2.17 on 2026-08-14 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm2_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityReviewAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('resolved', 'Resolved'), ('deferred', 'Deferred'), ('superseded', 'Superseded'), ('note_added', 'Note added')], max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('has_private_evidence', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cm2_identity_review_events', to=settings.AUTH_USER_MODEL)),
                ('review_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='cm2_review.identityreviewcase')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['review_case', 'created_at'], name='cm2_review__review__130e19_idx')],
            },
        ),
    ]
