# Generated by Django 5.2.17 on 2026-08-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm2_review', '0002_identityreviewauditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityreviewcase',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('link_existing', 'Link existing'), ('confirm_new', 'Confirm new'), ('merge_people', 'Merge people'), ('link_civic_data', 'Link Civic-Data'), ('defer', 'Defer'), ('reject', 'Reject')], max_length=24),
        ),
    ]
