# Generated by Django 5.2.17 on 2026-08-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm2_review', '0004_alter_identityreviewcase_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityreviewcase',
            name='case_type',
            field=models.CharField(choices=[('person_identity', 'New Person'), ('fuzzy_person_match', 'Fuzzy person match'), ('unresolved_result_choice', 'Unmatched Write-in')], max_length=32),
        ),
    ]
