# Generated by Django 5.2.17 on 2026-08-17 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm2_elections', '0002_lifecycleauditevent'),
        ('cm2_results', '0001_initial'),
        ('cm2_review', '0005_alter_identityreviewcase_case_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='identityreviewcase',
            name='cm2_review_case_subject_required',
        ),
        migrations.AddField(
            model_name='identityreviewcase',
            name='resolution_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='identityreviewcase',
            name='case_type',
            field=models.CharField(choices=[('person_identity', 'New Person'), ('fuzzy_person_match', 'Fuzzy person match'), ('unresolved_result_choice', 'Unmatched Write-in'), ('incomplete_election_data', 'Incomplete election data')], max_length=32),
        ),
        migrations.AlterField(
            model_name='identityreviewcase',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('link_existing', 'Link existing'), ('confirm_new', 'Confirm new'), ('merge_people', 'Merge people'), ('link_civic_data', 'Link Civic-Data'), ('defer', 'Defer'), ('reject', 'Reject'), ('supply_missing_data', 'Supply missing data')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='identityreviewcase',
            constraint=models.CheckConstraint(condition=models.Q(('source_record__isnull', False), ('provisional_person__isnull', False), ('result_choice__isnull', False), ('case_type', 'incomplete_election_data'), _connector='OR'), name='cm2_review_case_subject_required'),
        ),
    ]
