# Generated by Django 6.0.2 on 2026-05-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectionCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_year", models.IntegerField(unique=True)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("cycle_start", models.DateField()),
                ("cycle_end", models.DateField()),
            ],
            options={
                "ordering": ["-cycle_year"],
            },
        ),
        migrations.CreateModel(
            name="DistrictRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("district_type", models.CharField(max_length=50)),
                ("district_number", models.CharField(blank=True, max_length=20)),
                ("ocd_division_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("fips_code", models.CharField(blank=True, max_length=20)),
                ("election_year_valid", models.IntegerField(blank=True, null=True)),
                ("approximate", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "district_type"],
                        name="elections_d_state_3a1749_idx",
                    )
                ],
                "unique_together": {("ocd_division_id", "election_year_valid")},
            },
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("election_date", models.DateField()),
                (
                    "jurisdiction_level",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("local", "Local"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("source_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("results_pending", "Results Pending"),
                            ("results_certified", "Results Certified"),
                            ("archived", "Archived"),
                        ],
                        default="upcoming",
                        max_length=30,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("results_url", models.URLField(blank=True)),
                (
                    "election_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elections",
                        to="elections.electioncycle",
                    ),
                ),
            ],
            options={
                "ordering": ["election_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race_type",
                    models.CharField(
                        choices=[("candidate", "Candidate"), ("measure", "Measure")],
                        max_length=20,
                    ),
                ),
                ("office_title", models.CharField(max_length=255)),
                ("jurisdiction", models.CharField(max_length=255)),
                ("geography_scope", models.CharField(max_length=50)),
                ("voting_opens", models.DateTimeField(blank=True, null=True)),
                ("voting_closes", models.DateTimeField(blank=True, null=True)),
                (
                    "certification_status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("results_pending", "Results Pending"),
                            ("results_certified", "Results Certified"),
                            ("partial_results", "Partial Results"),
                        ],
                        default="upcoming",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("civic_api", "Civic API"),
                            ("openelections", "OpenElections"),
                            ("medsl", "MEDSL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_links", models.JSONField(blank=True, default=list)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "race_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "vote_method",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multi_seat", "Multi Seat"),
                            ("ranked_choice", "Ranked Choice"),
                            ("yes_no", "Yes / No"),
                        ],
                        default="single_choice",
                        max_length=20,
                    ),
                ),
                ("max_selections", models.PositiveIntegerField(default=1)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("ocd_division_id", models.CharField(blank=True, max_length=255)),
                (
                    "normalized_office_title",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("ballot_type", models.CharField(blank=True, max_length=100)),
                ("yes_vote_details", models.TextField(blank=True)),
                ("no_vote_details", models.TextField(blank=True)),
                ("supporting_links", models.JSONField(blank=True, default=list)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "match_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("verified", "Verified"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="verified",
                        max_length=20,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "ordering": ["office_title"],
            },
        ),
        migrations.CreateModel(
            name="MeasureOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_label", models.CharField(max_length=100)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_options",
                        to="elections.race",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("party", models.CharField(blank=True, max_length=100)),
                ("incumbent", models.BooleanField(default=False)),
                (
                    "candidate_status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("withdrawn", "Withdrawn"),
                            ("disqualified", "Disqualified"),
                            ("write_in", "Write-in"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "fec_candidate_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "bioguide_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("openstates_person_id", models.CharField(blank=True, max_length=50)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("contact_office", models.CharField(blank=True, max_length=255)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="elections.race",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="election",
            index=models.Index(
                fields=["source_id"], name="elections_e_source__eec5c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["election", "race_status", "certification_status"],
                name="elections_r_electio_40d092_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["geography_scope"], name="elections_r_geograp_3758f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_selections__gte", 1)),
                name="race_max_selections_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="measureoption",
            constraint=models.UniqueConstraint(
                fields=("race", "option_label"), name="unique_measure_option_per_race"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("race", "name"), name="unique_candidate_name_per_race"
            ),
        ),
    ]
