# Generated by Django 5.2.14 on 2026-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_drop_race_orphaned_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='source',
            field=models.CharField(choices=[('civic_api', 'Civic API'), ('openelections', 'OpenElections'), ('medsl', 'MEDSL'), ('community', 'Community'), ('results_adapter', 'Results Adapter'), ('sc_vrems', 'SC VREMS'), ('ia_sos', 'Iowa SOS')], max_length=20),
        ),
    ]
