# Generated by Django 5.2.14 on 2026-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_add_co_sos_race_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='source',
            field=models.CharField(choices=[('civic_api', 'Civic API'), ('openelections', 'OpenElections'), ('medsl', 'MEDSL'), ('community', 'Community'), ('results_adapter', 'Results Adapter'), ('sc_vrems', 'SC VREMS'), ('ia_sos', 'Iowa SOS'), ('co_sos', 'Colorado SOS'), ('va_elect', 'Virginia ELECT')], max_length=20),
        ),
    ]
