# Generated by Django 5.2.14 on 2026-05-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_add_va_elect_race_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('primary', 'Primary'), ('special', 'Special'), ('municipal', 'Municipal'), ('party', 'Party'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
