# Generated by Django 5.2.14 on 2026-05-28 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0013_ca_sos_race_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='field_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='normalized_party',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='election',
            name='canonical_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='election',
            name='contributing_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='election',
            name='field_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='election',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='contributing_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='race',
            name='field_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='election',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ElectionSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('results_url', models.URLField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links_rel', to='elections.election')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('election', 'source'), name='unique_election_source')],
            },
        ),
    ]
