# Generated by Django 5.2.14 on 2026-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_race_results_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='contributing_sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
