# Generated by Django 5.2.14 on 2026-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_fl_ew_race_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('primary', 'Primary'), ('primary_runoff', 'Primary Runoff'), ('special', 'Special'), ('general_runoff', 'General Runoff'), ('municipal', 'Municipal'), ('party', 'Party'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='race',
            name='source',
            field=models.CharField(choices=[('civic_api', 'Civic API'), ('openelections', 'OpenElections'), ('medsl', 'MEDSL'), ('community', 'Community'), ('results_adapter', 'Results Adapter'), ('sc_vrems', 'SC VREMS'), ('ia_sos', 'Iowa SOS'), ('co_sos', 'Colorado SOS'), ('va_elect', 'Virginia ELECT'), ('ma_sos', 'Massachusetts SOS'), ('ca_sos', 'California SOS'), ('wa_votewa', 'Washington VoteWA'), ('fl_ew', 'Florida Election Watch'), ('tx_goelect', 'Texas GoElect')], max_length=20),
        ),
    ]
