# Generated by Django 5.2.15 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0024_add_ky_sos_race_source"),
        ("elections", "0024_add_tn_sos_race_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="source",
            field=models.CharField(
                choices=[
                    ("civic_api", "Civic API"),
                    ("openelections", "OpenElections"),
                    ("medsl", "MEDSL"),
                    ("community", "Community"),
                    ("results_adapter", "Results Adapter"),
                    ("sc_vrems", "SC VREMS"),
                    ("ia_sos", "Iowa SOS"),
                    ("co_sos", "Colorado SOS"),
                    ("va_elect", "Virginia ELECT"),
                    ("ma_sos", "Massachusetts SOS"),
                    ("ca_sos", "California SOS"),
                    ("wa_votewa", "Washington VoteWA"),
                    ("fl_ew", "Florida Election Watch"),
                    ("tx_goelect", "Texas GoElect"),
                    ("oh_sos", "Ohio SOS"),
                    ("ga_sos", "Georgia SOS"),
                    ("il_sbe", "Illinois SBE"),
                    ("mn_sos", "Minnesota SOS"),
                    ("tn_sos", "Tennessee SOS"),
                    ("or_sos", "Oregon SOS"),
                    ("ky_sos", "Kentucky SOS"),
                ],
                max_length=20,
            ),
        ),
    ]
