# Generated by Django 5.2.15 on 2026-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0029_add_ny_boe_race_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ocpf_filer_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
