# Generated by Django 5.2.15 on 2026-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0030_candidate_ocpf_filer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='normalized_party',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='race',
            name='party',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
