# Generated by Django 5.2.14 on 2026-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0031_add_race_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
