# Generated by Django 5.2.15 on 2026-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0032_widen_candidate_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='canonical_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='normalized_office_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='office_title',
            field=models.TextField(),
        ),
    ]
