# Generated by Django 5.2.17 on 2026-08-13 20:55

import cm2_core.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=cm2_core.models.generate_public_id, editable=False, max_length=255, unique=True)),
                ('source_system', models.CharField(max_length=64)),
                ('source_type', models.CharField(choices=[('elections', 'Election discovery'), ('candidates', 'Candidate filing'), ('results', 'Election results'), ('certification', 'Certification evidence'), ('civic_data', 'Civic-Data snapshot'), ('other', 'Other')], max_length=32)),
                ('url', models.URLField(max_length=2048)),
                ('retrieved_at', models.DateTimeField()),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Checksum must contain exactly 64 lowercase hexadecimal characters.', regex='^[0-9a-f]{64}$')])),
                ('parser_version', models.CharField(max_length=64)),
                ('election_date', models.DateField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('retrieved', 'Retrieved'), ('validated', 'Validated'), ('applied', 'Applied'), ('unchanged', 'Unchanged'), ('failed', 'Failed')], default='retrieved', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor_versions', to='cm2_core.sourceartifact')),
            ],
            options={
                'ordering': ['-retrieved_at', 'source_system'],
                'indexes': [models.Index(fields=['source_system', 'source_type', 'election_date'], name='cm2_core_so_source__296af3_idx'), models.Index(fields=['processing_status'], name='cm2_core_so_process_5c63ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'url', 'content_sha256'), name='cm2_artifact_source_url_checksum_uniq')],
            },
        ),
    ]
