# Generated by Django 6.0.2 on 2026-05-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("task_name", models.CharField(blank=True, max_length=100)),
                ("address_label", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("completed_with_warnings", "Completed with Warnings"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=30,
                    ),
                ),
                ("cycle_year", models.IntegerField(blank=True, null=True)),
                ("records_skipped", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "election",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("civic", "Google Civic"),
                            ("fec", "OpenFEC"),
                            ("congress", "Congress Legislators"),
                            ("openstates", "Open States"),
                            ("census", "U.S. Census"),
                            ("openelections", "OpenElections"),
                            ("medsl", "MEDSL"),
                        ],
                        max_length=30,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("raw_payload", models.JSONField()),
                ("payload_checksum", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_records",
                        to="elections.candidate",
                    ),
                ),
                (
                    "linked_race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_records",
                        to="elections.race",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "external_id"],
                        name="ops_sourcer_source_1047e5_idx",
                    ),
                    models.Index(
                        fields=["linked_race"], name="ops_sourcer_linked__af589c_idx"
                    ),
                ],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
